# Generated by Django 4.1.13 on 2024-05-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_coin_featured_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='is_deleted',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
    ]
