# Generated by Django 4.1.13 on 2024-06-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0008_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
