# Generated by Django 4.1.13 on 2024-06-05 17:24

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0012_cartitemlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemlog',
            name='cart_item',
            field=djongo.models.fields.ArrayReferenceField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coins.cartitem'),
        ),
    ]
